// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package vfs

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *DiskUsage) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_965f3afadc761adf_1 = 3

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_965f3afadc761adf_1 uint32
	totalEncodedFields0zgensym_965f3afadc761adf_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_965f3afadc761adf_1 := totalEncodedFields0zgensym_965f3afadc761adf_1
	missingFieldsLeft0zgensym_965f3afadc761adf_1 := maxFields0zgensym_965f3afadc761adf_1 - totalEncodedFields0zgensym_965f3afadc761adf_1

	var nextMiss0zgensym_965f3afadc761adf_1 int32 = -1
	var found0zgensym_965f3afadc761adf_1 [maxFields0zgensym_965f3afadc761adf_1]bool
	var curField0zgensym_965f3afadc761adf_1 string

doneWithStruct0zgensym_965f3afadc761adf_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_965f3afadc761adf_1 > 0 || missingFieldsLeft0zgensym_965f3afadc761adf_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_965f3afadc761adf_1, missingFieldsLeft0zgensym_965f3afadc761adf_1, msgp.ShowFound(found0zgensym_965f3afadc761adf_1[:]), decodeMsgFieldOrder0zgensym_965f3afadc761adf_1)
		if encodedFieldsLeft0zgensym_965f3afadc761adf_1 > 0 {
			encodedFieldsLeft0zgensym_965f3afadc761adf_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_965f3afadc761adf_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_965f3afadc761adf_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_965f3afadc761adf_1 = 0
			}
			for nextMiss0zgensym_965f3afadc761adf_1 < maxFields0zgensym_965f3afadc761adf_1 && (found0zgensym_965f3afadc761adf_1[nextMiss0zgensym_965f3afadc761adf_1] || decodeMsgFieldSkip0zgensym_965f3afadc761adf_1[nextMiss0zgensym_965f3afadc761adf_1]) {
				nextMiss0zgensym_965f3afadc761adf_1++
			}
			if nextMiss0zgensym_965f3afadc761adf_1 == maxFields0zgensym_965f3afadc761adf_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_965f3afadc761adf_1
			}
			missingFieldsLeft0zgensym_965f3afadc761adf_1--
			curField0zgensym_965f3afadc761adf_1 = decodeMsgFieldOrder0zgensym_965f3afadc761adf_1[nextMiss0zgensym_965f3afadc761adf_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_965f3afadc761adf_1)
		switch curField0zgensym_965f3afadc761adf_1 {
		// -- templateDecodeMsg ends here --

		case "AvailBytes__u64":
			found0zgensym_965f3afadc761adf_1[0] = true
			z.AvailBytes, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "TotalBytes__u64":
			found0zgensym_965f3afadc761adf_1[1] = true
			z.TotalBytes, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "UsedBytes__u64":
			found0zgensym_965f3afadc761adf_1[2] = true
			z.UsedBytes, err = dc.ReadUint64()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_965f3afadc761adf_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of DiskUsage
var decodeMsgFieldOrder0zgensym_965f3afadc761adf_1 = []string{"AvailBytes__u64", "TotalBytes__u64", "UsedBytes__u64"}

var decodeMsgFieldSkip0zgensym_965f3afadc761adf_1 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *DiskUsage) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = (z.AvailBytes == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.TotalBytes == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.UsedBytes == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *DiskUsage) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_965f3afadc761adf_2 [3]bool
	fieldsInUse_zgensym_965f3afadc761adf_3 := z.fieldsNotEmpty(empty_zgensym_965f3afadc761adf_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_965f3afadc761adf_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'DiskUsage'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_965f3afadc761adf_2[0] {
		// write "AvailBytes__u64"
		err = en.Append(0xaf, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.AvailBytes)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_2[1] {
		// write "TotalBytes__u64"
		err = en.Append(0xaf, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.TotalBytes)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_2[2] {
		// write "UsedBytes__u64"
		err = en.Append(0xae, 0x55, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.UsedBytes)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DiskUsage) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "AvailBytes__u64"
		o = append(o, 0xaf, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.AvailBytes)
	}

	if !empty[1] {
		// string "TotalBytes__u64"
		o = append(o, 0xaf, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.TotalBytes)
	}

	if !empty[2] {
		// string "UsedBytes__u64"
		o = append(o, 0xae, 0x55, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.UsedBytes)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DiskUsage) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *DiskUsage) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_965f3afadc761adf_5 = 3

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_965f3afadc761adf_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_965f3afadc761adf_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_965f3afadc761adf_5 := totalEncodedFields4zgensym_965f3afadc761adf_5
	missingFieldsLeft4zgensym_965f3afadc761adf_5 := maxFields4zgensym_965f3afadc761adf_5 - totalEncodedFields4zgensym_965f3afadc761adf_5

	var nextMiss4zgensym_965f3afadc761adf_5 int32 = -1
	var found4zgensym_965f3afadc761adf_5 [maxFields4zgensym_965f3afadc761adf_5]bool
	var curField4zgensym_965f3afadc761adf_5 string

doneWithStruct4zgensym_965f3afadc761adf_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_965f3afadc761adf_5 > 0 || missingFieldsLeft4zgensym_965f3afadc761adf_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_965f3afadc761adf_5, missingFieldsLeft4zgensym_965f3afadc761adf_5, msgp.ShowFound(found4zgensym_965f3afadc761adf_5[:]), unmarshalMsgFieldOrder4zgensym_965f3afadc761adf_5)
		if encodedFieldsLeft4zgensym_965f3afadc761adf_5 > 0 {
			encodedFieldsLeft4zgensym_965f3afadc761adf_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_965f3afadc761adf_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_965f3afadc761adf_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_965f3afadc761adf_5 = 0
			}
			for nextMiss4zgensym_965f3afadc761adf_5 < maxFields4zgensym_965f3afadc761adf_5 && (found4zgensym_965f3afadc761adf_5[nextMiss4zgensym_965f3afadc761adf_5] || unmarshalMsgFieldSkip4zgensym_965f3afadc761adf_5[nextMiss4zgensym_965f3afadc761adf_5]) {
				nextMiss4zgensym_965f3afadc761adf_5++
			}
			if nextMiss4zgensym_965f3afadc761adf_5 == maxFields4zgensym_965f3afadc761adf_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_965f3afadc761adf_5
			}
			missingFieldsLeft4zgensym_965f3afadc761adf_5--
			curField4zgensym_965f3afadc761adf_5 = unmarshalMsgFieldOrder4zgensym_965f3afadc761adf_5[nextMiss4zgensym_965f3afadc761adf_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_965f3afadc761adf_5)
		switch curField4zgensym_965f3afadc761adf_5 {
		// -- templateUnmarshalMsg ends here --

		case "AvailBytes__u64":
			found4zgensym_965f3afadc761adf_5[0] = true
			z.AvailBytes, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "TotalBytes__u64":
			found4zgensym_965f3afadc761adf_5[1] = true
			z.TotalBytes, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "UsedBytes__u64":
			found4zgensym_965f3afadc761adf_5[2] = true
			z.UsedBytes, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_965f3afadc761adf_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of DiskUsage
var unmarshalMsgFieldOrder4zgensym_965f3afadc761adf_5 = []string{"AvailBytes__u64", "TotalBytes__u64", "UsedBytes__u64"}

var unmarshalMsgFieldSkip4zgensym_965f3afadc761adf_5 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DiskUsage) Msgsize() (s int) {
	s = 1 + 16 + msgp.Uint64Size + 16 + msgp.Uint64Size + 15 + msgp.Uint64Size
	return
}
func (z *DiskUsage) Gstring() (r string) {
	r = "&DiskUsage{\n"
	r += fmt.Sprintf("AvailBytes: %v,\n", z.AvailBytes)
	r += fmt.Sprintf("TotalBytes: %v,\n", z.TotalBytes)
	r += fmt.Sprintf(" UsedBytes: %v,\n", z.UsedBytes)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *SerzMemFS) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields8zgensym_965f3afadc761adf_9 = 6

	// -- templateDecodeMsg starts here--
	var totalEncodedFields8zgensym_965f3afadc761adf_9 uint32
	totalEncodedFields8zgensym_965f3afadc761adf_9, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft8zgensym_965f3afadc761adf_9 := totalEncodedFields8zgensym_965f3afadc761adf_9
	missingFieldsLeft8zgensym_965f3afadc761adf_9 := maxFields8zgensym_965f3afadc761adf_9 - totalEncodedFields8zgensym_965f3afadc761adf_9

	var nextMiss8zgensym_965f3afadc761adf_9 int32 = -1
	var found8zgensym_965f3afadc761adf_9 [maxFields8zgensym_965f3afadc761adf_9]bool
	var curField8zgensym_965f3afadc761adf_9 string

doneWithStruct8zgensym_965f3afadc761adf_9:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft8zgensym_965f3afadc761adf_9 > 0 || missingFieldsLeft8zgensym_965f3afadc761adf_9 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft8zgensym_965f3afadc761adf_9, missingFieldsLeft8zgensym_965f3afadc761adf_9, msgp.ShowFound(found8zgensym_965f3afadc761adf_9[:]), decodeMsgFieldOrder8zgensym_965f3afadc761adf_9)
		if encodedFieldsLeft8zgensym_965f3afadc761adf_9 > 0 {
			encodedFieldsLeft8zgensym_965f3afadc761adf_9--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField8zgensym_965f3afadc761adf_9 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss8zgensym_965f3afadc761adf_9 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss8zgensym_965f3afadc761adf_9 = 0
			}
			for nextMiss8zgensym_965f3afadc761adf_9 < maxFields8zgensym_965f3afadc761adf_9 && (found8zgensym_965f3afadc761adf_9[nextMiss8zgensym_965f3afadc761adf_9] || decodeMsgFieldSkip8zgensym_965f3afadc761adf_9[nextMiss8zgensym_965f3afadc761adf_9]) {
				nextMiss8zgensym_965f3afadc761adf_9++
			}
			if nextMiss8zgensym_965f3afadc761adf_9 == maxFields8zgensym_965f3afadc761adf_9 {
				// filled all the empty fields!
				break doneWithStruct8zgensym_965f3afadc761adf_9
			}
			missingFieldsLeft8zgensym_965f3afadc761adf_9--
			curField8zgensym_965f3afadc761adf_9 = decodeMsgFieldOrder8zgensym_965f3afadc761adf_9[nextMiss8zgensym_965f3afadc761adf_9]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField8zgensym_965f3afadc761adf_9)
		switch curField8zgensym_965f3afadc761adf_9 {
		// -- templateDecodeMsg ends here --

		case "Root__ptr":
			found8zgensym_965f3afadc761adf_9[0] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.Root != nil {
					dc.PushAlwaysNil()
					err = z.Root.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.Root == nil {
					z.Root = new(SerzMemNode)
				}

				err = z.Root.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		case "Crashable__boo":
			found8zgensym_965f3afadc761adf_9[2] = true
			z.Crashable, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "WindowsSemantics__boo":
			found8zgensym_965f3afadc761adf_9[3] = true
			z.WindowsSemantics, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "Usage__rct":
			found8zgensym_965f3afadc761adf_9[4] = true
			const maxFields10zgensym_965f3afadc761adf_11 = 3

			// -- templateDecodeMsg starts here--
			var totalEncodedFields10zgensym_965f3afadc761adf_11 uint32
			totalEncodedFields10zgensym_965f3afadc761adf_11, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			encodedFieldsLeft10zgensym_965f3afadc761adf_11 := totalEncodedFields10zgensym_965f3afadc761adf_11
			missingFieldsLeft10zgensym_965f3afadc761adf_11 := maxFields10zgensym_965f3afadc761adf_11 - totalEncodedFields10zgensym_965f3afadc761adf_11

			var nextMiss10zgensym_965f3afadc761adf_11 int32 = -1
			var found10zgensym_965f3afadc761adf_11 [maxFields10zgensym_965f3afadc761adf_11]bool
			var curField10zgensym_965f3afadc761adf_11 string

		doneWithStruct10zgensym_965f3afadc761adf_11:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft10zgensym_965f3afadc761adf_11 > 0 || missingFieldsLeft10zgensym_965f3afadc761adf_11 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft10zgensym_965f3afadc761adf_11, missingFieldsLeft10zgensym_965f3afadc761adf_11, msgp.ShowFound(found10zgensym_965f3afadc761adf_11[:]), decodeMsgFieldOrder10zgensym_965f3afadc761adf_11)
				if encodedFieldsLeft10zgensym_965f3afadc761adf_11 > 0 {
					encodedFieldsLeft10zgensym_965f3afadc761adf_11--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						return
					}
					curField10zgensym_965f3afadc761adf_11 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss10zgensym_965f3afadc761adf_11 < 0 {
						// tell the reader to only give us Nils
						// until further notice.
						dc.PushAlwaysNil()
						nextMiss10zgensym_965f3afadc761adf_11 = 0
					}
					for nextMiss10zgensym_965f3afadc761adf_11 < maxFields10zgensym_965f3afadc761adf_11 && (found10zgensym_965f3afadc761adf_11[nextMiss10zgensym_965f3afadc761adf_11] || decodeMsgFieldSkip10zgensym_965f3afadc761adf_11[nextMiss10zgensym_965f3afadc761adf_11]) {
						nextMiss10zgensym_965f3afadc761adf_11++
					}
					if nextMiss10zgensym_965f3afadc761adf_11 == maxFields10zgensym_965f3afadc761adf_11 {
						// filled all the empty fields!
						break doneWithStruct10zgensym_965f3afadc761adf_11
					}
					missingFieldsLeft10zgensym_965f3afadc761adf_11--
					curField10zgensym_965f3afadc761adf_11 = decodeMsgFieldOrder10zgensym_965f3afadc761adf_11[nextMiss10zgensym_965f3afadc761adf_11]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField10zgensym_965f3afadc761adf_11)
				switch curField10zgensym_965f3afadc761adf_11 {
				// -- templateDecodeMsg ends here --

				case "AvailBytes__u64":
					found10zgensym_965f3afadc761adf_11[0] = true
					z.Usage.AvailBytes, err = dc.ReadUint64()
					if err != nil {
						return
					}
				case "TotalBytes__u64":
					found10zgensym_965f3afadc761adf_11[1] = true
					z.Usage.TotalBytes, err = dc.ReadUint64()
					if err != nil {
						return
					}
				case "UsedBytes__u64":
					found10zgensym_965f3afadc761adf_11[2] = true
					z.Usage.UsedBytes, err = dc.ReadUint64()
					if err != nil {
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						return
					}
				}
			}
			if nextMiss10zgensym_965f3afadc761adf_11 != -1 {
				dc.PopAlwaysNil()
			}

		case "Mounts__map":
			found8zgensym_965f3afadc761adf_9[5] = true
			var zgensym_965f3afadc761adf_12 uint32
			zgensym_965f3afadc761adf_12, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.Mounts == nil && zgensym_965f3afadc761adf_12 > 0 {
				z.Mounts = make(map[string]string, zgensym_965f3afadc761adf_12)
			} else if len(z.Mounts) > 0 {
				for key, _ := range z.Mounts {
					delete(z.Mounts, key)
				}
			}
			for zgensym_965f3afadc761adf_12 > 0 {
				zgensym_965f3afadc761adf_12--
				var zgensym_965f3afadc761adf_6 string
				var zgensym_965f3afadc761adf_7 string
				zgensym_965f3afadc761adf_6, err = dc.ReadString()
				if err != nil {
					return
				}
				zgensym_965f3afadc761adf_7, err = dc.ReadString()
				if err != nil {
					return
				}
				z.Mounts[zgensym_965f3afadc761adf_6] = zgensym_965f3afadc761adf_7
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss8zgensym_965f3afadc761adf_9 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of SerzMemFS
var decodeMsgFieldOrder8zgensym_965f3afadc761adf_9 = []string{"Root__ptr", "", "Crashable__boo", "WindowsSemantics__boo", "Usage__rct", "Mounts__map"}

var decodeMsgFieldSkip8zgensym_965f3afadc761adf_9 = []bool{false, true, false, false, false, false}

// fields of DiskUsage
var decodeMsgFieldOrder10zgensym_965f3afadc761adf_11 = []string{"AvailBytes__u64", "TotalBytes__u64", "UsedBytes__u64"}

var decodeMsgFieldSkip10zgensym_965f3afadc761adf_11 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *SerzMemFS) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 5
	}
	var fieldsInUse uint32 = 5
	isempty[0] = (z.Root == nil) // pointer, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[2] = (!z.Crashable) // bool, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (!z.WindowsSemantics) // bool, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = false // struct values are never empty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.Mounts) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *SerzMemFS) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_965f3afadc761adf_13 [6]bool
	fieldsInUse_zgensym_965f3afadc761adf_14 := z.fieldsNotEmpty(empty_zgensym_965f3afadc761adf_13[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_965f3afadc761adf_14 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'SerzMemFS'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x53, 0x65, 0x72, 0x7a, 0x4d, 0x65, 0x6d, 0x46, 0x53})
	if err != nil {
		return err
	}

	if !empty_zgensym_965f3afadc761adf_13[0] {
		// write "Root__ptr"
		err = en.Append(0xa9, 0x52, 0x6f, 0x6f, 0x74, 0x5f, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.Root == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Root.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}

	if !empty_zgensym_965f3afadc761adf_13[2] {
		// write "Crashable__boo"
		err = en.Append(0xae, 0x43, 0x72, 0x61, 0x73, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		if err != nil {
			return err
		}
		err = en.WriteBool(z.Crashable)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_13[3] {
		// write "WindowsSemantics__boo"
		err = en.Append(0xb5, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		if err != nil {
			return err
		}
		err = en.WriteBool(z.WindowsSemantics)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_13[4] {
		// write "Usage__rct"
		err = en.Append(0xaa, 0x55, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x5f, 0x72, 0x63, 0x74)
		if err != nil {
			return err
		}

		// honor the omitempty tags
		var empty_zgensym_965f3afadc761adf_15 [3]bool
		fieldsInUse_zgensym_965f3afadc761adf_16 := z.Usage.fieldsNotEmpty(empty_zgensym_965f3afadc761adf_15[:])

		// map header
		err = en.WriteMapHeader(fieldsInUse_zgensym_965f3afadc761adf_16 + 1)
		if err != nil {
			return err
		}

		// runtime struct type identification for 'DiskUsage'
		err = en.Append(0xa1, 0x40)
		if err != nil {
			return err
		}
		err = en.WriteStringFromBytes([]byte{0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65})
		if err != nil {
			return err
		}

		if !empty_zgensym_965f3afadc761adf_15[0] {
			// write "AvailBytes__u64"
			err = en.Append(0xaf, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteUint64(z.Usage.AvailBytes)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_965f3afadc761adf_15[1] {
			// write "TotalBytes__u64"
			err = en.Append(0xaf, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteUint64(z.Usage.TotalBytes)
			if err != nil {
				return
			}
		}

		if !empty_zgensym_965f3afadc761adf_15[2] {
			// write "UsedBytes__u64"
			err = en.Append(0xae, 0x55, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			if err != nil {
				return err
			}
			err = en.WriteUint64(z.Usage.UsedBytes)
			if err != nil {
				return
			}
		}

	}

	if !empty_zgensym_965f3afadc761adf_13[5] {
		// write "Mounts__map"
		err = en.Append(0xab, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		if err != nil {
			return err
		}
		err = en.WriteMapHeader(uint32(len(z.Mounts)))
		if err != nil {
			return
		}
		for zgensym_965f3afadc761adf_6, zgensym_965f3afadc761adf_7 := range z.Mounts {
			err = en.WriteString(zgensym_965f3afadc761adf_6)
			if err != nil {
				return
			}
			err = en.WriteString(zgensym_965f3afadc761adf_7)
			if err != nil {
				return
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SerzMemFS) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [6]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Root__ptr"
		o = append(o, 0xa9, 0x52, 0x6f, 0x6f, 0x74, 0x5f, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.Root == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.Root.MarshalMsg(o) // not is.iface
			if err != nil {
				return
			}
		}
	}

	if !empty[2] {
		// string "Crashable__boo"
		o = append(o, 0xae, 0x43, 0x72, 0x61, 0x73, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		o = msgp.AppendBool(o, z.Crashable)
	}

	if !empty[3] {
		// string "WindowsSemantics__boo"
		o = append(o, 0xb5, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		o = msgp.AppendBool(o, z.WindowsSemantics)
	}

	if !empty[4] {
		// string "Usage__rct"
		o = append(o, 0xaa, 0x55, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x5f, 0x72, 0x63, 0x74)

		// honor the omitempty tags
		var empty [3]bool
		fieldsInUse := z.Usage.fieldsNotEmpty(empty[:])
		o = msgp.AppendMapHeader(o, fieldsInUse)

		if !empty[0] {
			// string "AvailBytes__u64"
			o = append(o, 0xaf, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			o = msgp.AppendUint64(o, z.Usage.AvailBytes)
		}

		if !empty[1] {
			// string "TotalBytes__u64"
			o = append(o, 0xaf, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			o = msgp.AppendUint64(o, z.Usage.TotalBytes)
		}

		if !empty[2] {
			// string "UsedBytes__u64"
			o = append(o, 0xae, 0x55, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x5f, 0x75, 0x36, 0x34)
			o = msgp.AppendUint64(o, z.Usage.UsedBytes)
		}

	}

	if !empty[5] {
		// string "Mounts__map"
		o = append(o, 0xab, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		o = msgp.AppendMapHeader(o, uint32(len(z.Mounts)))
		for zgensym_965f3afadc761adf_6, zgensym_965f3afadc761adf_7 := range z.Mounts {
			o = msgp.AppendString(o, zgensym_965f3afadc761adf_6)
			o = msgp.AppendString(o, zgensym_965f3afadc761adf_7)
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SerzMemFS) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *SerzMemFS) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields17zgensym_965f3afadc761adf_18 = 6

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields17zgensym_965f3afadc761adf_18 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields17zgensym_965f3afadc761adf_18, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft17zgensym_965f3afadc761adf_18 := totalEncodedFields17zgensym_965f3afadc761adf_18
	missingFieldsLeft17zgensym_965f3afadc761adf_18 := maxFields17zgensym_965f3afadc761adf_18 - totalEncodedFields17zgensym_965f3afadc761adf_18

	var nextMiss17zgensym_965f3afadc761adf_18 int32 = -1
	var found17zgensym_965f3afadc761adf_18 [maxFields17zgensym_965f3afadc761adf_18]bool
	var curField17zgensym_965f3afadc761adf_18 string

doneWithStruct17zgensym_965f3afadc761adf_18:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft17zgensym_965f3afadc761adf_18 > 0 || missingFieldsLeft17zgensym_965f3afadc761adf_18 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft17zgensym_965f3afadc761adf_18, missingFieldsLeft17zgensym_965f3afadc761adf_18, msgp.ShowFound(found17zgensym_965f3afadc761adf_18[:]), unmarshalMsgFieldOrder17zgensym_965f3afadc761adf_18)
		if encodedFieldsLeft17zgensym_965f3afadc761adf_18 > 0 {
			encodedFieldsLeft17zgensym_965f3afadc761adf_18--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField17zgensym_965f3afadc761adf_18 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss17zgensym_965f3afadc761adf_18 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss17zgensym_965f3afadc761adf_18 = 0
			}
			for nextMiss17zgensym_965f3afadc761adf_18 < maxFields17zgensym_965f3afadc761adf_18 && (found17zgensym_965f3afadc761adf_18[nextMiss17zgensym_965f3afadc761adf_18] || unmarshalMsgFieldSkip17zgensym_965f3afadc761adf_18[nextMiss17zgensym_965f3afadc761adf_18]) {
				nextMiss17zgensym_965f3afadc761adf_18++
			}
			if nextMiss17zgensym_965f3afadc761adf_18 == maxFields17zgensym_965f3afadc761adf_18 {
				// filled all the empty fields!
				break doneWithStruct17zgensym_965f3afadc761adf_18
			}
			missingFieldsLeft17zgensym_965f3afadc761adf_18--
			curField17zgensym_965f3afadc761adf_18 = unmarshalMsgFieldOrder17zgensym_965f3afadc761adf_18[nextMiss17zgensym_965f3afadc761adf_18]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField17zgensym_965f3afadc761adf_18)
		switch curField17zgensym_965f3afadc761adf_18 {
		// -- templateUnmarshalMsg ends here --

		case "Root__ptr":
			found17zgensym_965f3afadc761adf_18[0] = true
			// unmarshalGen.gPtr(): we have a BaseElem.

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.Root != nil {
					z.Root.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.Root {
						z.Root.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.Root == nil {
						z.Root = new(SerzMemNode)
					}

					bts, err = z.Root.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		case "Crashable__boo":
			found17zgensym_965f3afadc761adf_18[2] = true
			z.Crashable, bts, err = nbs.ReadBoolBytes(bts)

			if err != nil {
				return
			}
		case "WindowsSemantics__boo":
			found17zgensym_965f3afadc761adf_18[3] = true
			z.WindowsSemantics, bts, err = nbs.ReadBoolBytes(bts)

			if err != nil {
				return
			}
		case "Usage__rct":
			found17zgensym_965f3afadc761adf_18[4] = true
			const maxFields19zgensym_965f3afadc761adf_20 = 3

			// -- templateUnmarshalMsg starts here--
			var totalEncodedFields19zgensym_965f3afadc761adf_20 uint32
			if !nbs.AlwaysNil {
				totalEncodedFields19zgensym_965f3afadc761adf_20, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
			}
			encodedFieldsLeft19zgensym_965f3afadc761adf_20 := totalEncodedFields19zgensym_965f3afadc761adf_20
			missingFieldsLeft19zgensym_965f3afadc761adf_20 := maxFields19zgensym_965f3afadc761adf_20 - totalEncodedFields19zgensym_965f3afadc761adf_20

			var nextMiss19zgensym_965f3afadc761adf_20 int32 = -1
			var found19zgensym_965f3afadc761adf_20 [maxFields19zgensym_965f3afadc761adf_20]bool
			var curField19zgensym_965f3afadc761adf_20 string

		doneWithStruct19zgensym_965f3afadc761adf_20:
			// First fill all the encoded fields, then
			// treat the remaining, missing fields, as Nil.
			for encodedFieldsLeft19zgensym_965f3afadc761adf_20 > 0 || missingFieldsLeft19zgensym_965f3afadc761adf_20 > 0 {
				//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft19zgensym_965f3afadc761adf_20, missingFieldsLeft19zgensym_965f3afadc761adf_20, msgp.ShowFound(found19zgensym_965f3afadc761adf_20[:]), unmarshalMsgFieldOrder19zgensym_965f3afadc761adf_20)
				if encodedFieldsLeft19zgensym_965f3afadc761adf_20 > 0 {
					encodedFieldsLeft19zgensym_965f3afadc761adf_20--
					field, bts, err = nbs.ReadMapKeyZC(bts)
					if err != nil {
						return
					}
					curField19zgensym_965f3afadc761adf_20 = msgp.UnsafeString(field)
				} else {
					//missing fields need handling
					if nextMiss19zgensym_965f3afadc761adf_20 < 0 {
						// set bts to contain just mnil (0xc0)
						bts = nbs.PushAlwaysNil(bts)
						nextMiss19zgensym_965f3afadc761adf_20 = 0
					}
					for nextMiss19zgensym_965f3afadc761adf_20 < maxFields19zgensym_965f3afadc761adf_20 && (found19zgensym_965f3afadc761adf_20[nextMiss19zgensym_965f3afadc761adf_20] || unmarshalMsgFieldSkip19zgensym_965f3afadc761adf_20[nextMiss19zgensym_965f3afadc761adf_20]) {
						nextMiss19zgensym_965f3afadc761adf_20++
					}
					if nextMiss19zgensym_965f3afadc761adf_20 == maxFields19zgensym_965f3afadc761adf_20 {
						// filled all the empty fields!
						break doneWithStruct19zgensym_965f3afadc761adf_20
					}
					missingFieldsLeft19zgensym_965f3afadc761adf_20--
					curField19zgensym_965f3afadc761adf_20 = unmarshalMsgFieldOrder19zgensym_965f3afadc761adf_20[nextMiss19zgensym_965f3afadc761adf_20]
				}
				//fmt.Printf("switching on curField: '%v'\n", curField19zgensym_965f3afadc761adf_20)
				switch curField19zgensym_965f3afadc761adf_20 {
				// -- templateUnmarshalMsg ends here --

				case "AvailBytes__u64":
					found19zgensym_965f3afadc761adf_20[0] = true
					z.Usage.AvailBytes, bts, err = nbs.ReadUint64Bytes(bts)

					if err != nil {
						return
					}
				case "TotalBytes__u64":
					found19zgensym_965f3afadc761adf_20[1] = true
					z.Usage.TotalBytes, bts, err = nbs.ReadUint64Bytes(bts)

					if err != nil {
						return
					}
				case "UsedBytes__u64":
					found19zgensym_965f3afadc761adf_20[2] = true
					z.Usage.UsedBytes, bts, err = nbs.ReadUint64Bytes(bts)

					if err != nil {
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						return
					}
				}
			}
			if nextMiss19zgensym_965f3afadc761adf_20 != -1 {
				bts = nbs.PopAlwaysNil()
			}

		case "Mounts__map":
			found17zgensym_965f3afadc761adf_18[5] = true
			if nbs.AlwaysNil {
				if len(z.Mounts) > 0 {
					for key, _ := range z.Mounts {
						delete(z.Mounts, key)
					}
				}

			} else {

				var zgensym_965f3afadc761adf_21 uint32
				zgensym_965f3afadc761adf_21, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
				if z.Mounts == nil && zgensym_965f3afadc761adf_21 > 0 {
					z.Mounts = make(map[string]string, zgensym_965f3afadc761adf_21)
				} else if len(z.Mounts) > 0 {
					for key, _ := range z.Mounts {
						delete(z.Mounts, key)
					}
				}
				for zgensym_965f3afadc761adf_21 > 0 {
					var zgensym_965f3afadc761adf_6 string
					var zgensym_965f3afadc761adf_7 string
					zgensym_965f3afadc761adf_21--
					zgensym_965f3afadc761adf_6, bts, err = nbs.ReadStringBytes(bts)
					if err != nil {
						return
					}
					zgensym_965f3afadc761adf_7, bts, err = nbs.ReadStringBytes(bts)

					if err != nil {
						return
					}
					z.Mounts[zgensym_965f3afadc761adf_6] = zgensym_965f3afadc761adf_7
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss17zgensym_965f3afadc761adf_18 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of SerzMemFS
var unmarshalMsgFieldOrder17zgensym_965f3afadc761adf_18 = []string{"Root__ptr", "", "Crashable__boo", "WindowsSemantics__boo", "Usage__rct", "Mounts__map"}

var unmarshalMsgFieldSkip17zgensym_965f3afadc761adf_18 = []bool{false, true, false, false, false, false}

// fields of DiskUsage
var unmarshalMsgFieldOrder19zgensym_965f3afadc761adf_20 = []string{"AvailBytes__u64", "TotalBytes__u64", "UsedBytes__u64"}

var unmarshalMsgFieldSkip19zgensym_965f3afadc761adf_20 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SerzMemFS) Msgsize() (s int) {
	s = 1 + 10
	if z.Root == nil {
		s += msgp.NilSize
	} else {
		s += z.Root.Msgsize()
	}
	s += 15 + msgp.BoolSize + 22 + msgp.BoolSize + 11 + 1 + 16 + msgp.Uint64Size + 16 + msgp.Uint64Size + 15 + msgp.Uint64Size + 12 + msgp.MapHeaderSize
	if z.Mounts != nil {
		for zgensym_965f3afadc761adf_6, zgensym_965f3afadc761adf_7 := range z.Mounts {
			_ = zgensym_965f3afadc761adf_7
			_ = zgensym_965f3afadc761adf_6
			s += msgp.StringPrefixSize + len(zgensym_965f3afadc761adf_6) + msgp.StringPrefixSize + len(zgensym_965f3afadc761adf_7)
		}
	}
	return
}
func (z *SerzMemFS) Gstring() (r string) {
	r = "&SerzMemFS{\n"
	r += fmt.Sprintf("            Root: %v,\n", z.Root)
	r += fmt.Sprintf("       Crashable: %v,\n", z.Crashable)
	r += fmt.Sprintf("WindowsSemantics: %v,\n", z.WindowsSemantics)
	r += fmt.Sprintf("           Usage: %v,\n", z.Usage)
	r += fmt.Sprintf("          Mounts: %v,\n", z.Mounts)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *SerzMemNode) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields26zgensym_965f3afadc761adf_27 = 6

	// -- templateDecodeMsg starts here--
	var totalEncodedFields26zgensym_965f3afadc761adf_27 uint32
	totalEncodedFields26zgensym_965f3afadc761adf_27, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft26zgensym_965f3afadc761adf_27 := totalEncodedFields26zgensym_965f3afadc761adf_27
	missingFieldsLeft26zgensym_965f3afadc761adf_27 := maxFields26zgensym_965f3afadc761adf_27 - totalEncodedFields26zgensym_965f3afadc761adf_27

	var nextMiss26zgensym_965f3afadc761adf_27 int32 = -1
	var found26zgensym_965f3afadc761adf_27 [maxFields26zgensym_965f3afadc761adf_27]bool
	var curField26zgensym_965f3afadc761adf_27 string

doneWithStruct26zgensym_965f3afadc761adf_27:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft26zgensym_965f3afadc761adf_27 > 0 || missingFieldsLeft26zgensym_965f3afadc761adf_27 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft26zgensym_965f3afadc761adf_27, missingFieldsLeft26zgensym_965f3afadc761adf_27, msgp.ShowFound(found26zgensym_965f3afadc761adf_27[:]), decodeMsgFieldOrder26zgensym_965f3afadc761adf_27)
		if encodedFieldsLeft26zgensym_965f3afadc761adf_27 > 0 {
			encodedFieldsLeft26zgensym_965f3afadc761adf_27--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField26zgensym_965f3afadc761adf_27 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss26zgensym_965f3afadc761adf_27 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss26zgensym_965f3afadc761adf_27 = 0
			}
			for nextMiss26zgensym_965f3afadc761adf_27 < maxFields26zgensym_965f3afadc761adf_27 && (found26zgensym_965f3afadc761adf_27[nextMiss26zgensym_965f3afadc761adf_27] || decodeMsgFieldSkip26zgensym_965f3afadc761adf_27[nextMiss26zgensym_965f3afadc761adf_27]) {
				nextMiss26zgensym_965f3afadc761adf_27++
			}
			if nextMiss26zgensym_965f3afadc761adf_27 == maxFields26zgensym_965f3afadc761adf_27 {
				// filled all the empty fields!
				break doneWithStruct26zgensym_965f3afadc761adf_27
			}
			missingFieldsLeft26zgensym_965f3afadc761adf_27--
			curField26zgensym_965f3afadc761adf_27 = decodeMsgFieldOrder26zgensym_965f3afadc761adf_27[nextMiss26zgensym_965f3afadc761adf_27]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField26zgensym_965f3afadc761adf_27)
		switch curField26zgensym_965f3afadc761adf_27 {
		// -- templateDecodeMsg ends here --

		case "IsDir__boo":
			found26zgensym_965f3afadc761adf_27[0] = true
			z.IsDir, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "Data__bin":
			found26zgensym_965f3afadc761adf_27[1] = true
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				return
			}
		case "SyncedData__bin":
			found26zgensym_965f3afadc761adf_27[2] = true
			z.SyncedData, err = dc.ReadBytes(z.SyncedData)
			if err != nil {
				return
			}
		case "ModTime__tim":
			found26zgensym_965f3afadc761adf_27[3] = true
			z.ModTime, err = dc.ReadTime()
			if err != nil {
				return
			}
		case "Children__map":
			found26zgensym_965f3afadc761adf_27[4] = true
			var zgensym_965f3afadc761adf_28 uint32
			zgensym_965f3afadc761adf_28, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.Children == nil && zgensym_965f3afadc761adf_28 > 0 {
				z.Children = make(map[string]*SerzMemNode, zgensym_965f3afadc761adf_28)
			} else if len(z.Children) > 0 {
				for key, _ := range z.Children {
					delete(z.Children, key)
				}
			}
			for zgensym_965f3afadc761adf_28 > 0 {
				zgensym_965f3afadc761adf_28--
				var zgensym_965f3afadc761adf_22 string
				var zgensym_965f3afadc761adf_23 *SerzMemNode
				zgensym_965f3afadc761adf_22, err = dc.ReadString()
				if err != nil {
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					if zgensym_965f3afadc761adf_23 != nil {
						dc.PushAlwaysNil()
						err = zgensym_965f3afadc761adf_23.DecodeMsg(dc)
						if err != nil {
							return
						}
						dc.PopAlwaysNil()
					}
				} else {
					// not Nil, we have something to read

					if zgensym_965f3afadc761adf_23 == nil {
						zgensym_965f3afadc761adf_23 = new(SerzMemNode)
					}

					err = zgensym_965f3afadc761adf_23.DecodeMsg(dc)
					if err != nil {
						return
					}
				}
				z.Children[zgensym_965f3afadc761adf_22] = zgensym_965f3afadc761adf_23
			}
		case "SyncedChildren__map":
			found26zgensym_965f3afadc761adf_27[5] = true
			var zgensym_965f3afadc761adf_29 uint32
			zgensym_965f3afadc761adf_29, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.SyncedChildren == nil && zgensym_965f3afadc761adf_29 > 0 {
				z.SyncedChildren = make(map[string]*SerzMemNode, zgensym_965f3afadc761adf_29)
			} else if len(z.SyncedChildren) > 0 {
				for key, _ := range z.SyncedChildren {
					delete(z.SyncedChildren, key)
				}
			}
			for zgensym_965f3afadc761adf_29 > 0 {
				zgensym_965f3afadc761adf_29--
				var zgensym_965f3afadc761adf_24 string
				var zgensym_965f3afadc761adf_25 *SerzMemNode
				zgensym_965f3afadc761adf_24, err = dc.ReadString()
				if err != nil {
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					if zgensym_965f3afadc761adf_25 != nil {
						dc.PushAlwaysNil()
						err = zgensym_965f3afadc761adf_25.DecodeMsg(dc)
						if err != nil {
							return
						}
						dc.PopAlwaysNil()
					}
				} else {
					// not Nil, we have something to read

					if zgensym_965f3afadc761adf_25 == nil {
						zgensym_965f3afadc761adf_25 = new(SerzMemNode)
					}

					err = zgensym_965f3afadc761adf_25.DecodeMsg(dc)
					if err != nil {
						return
					}
				}
				z.SyncedChildren[zgensym_965f3afadc761adf_24] = zgensym_965f3afadc761adf_25
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss26zgensym_965f3afadc761adf_27 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of SerzMemNode
var decodeMsgFieldOrder26zgensym_965f3afadc761adf_27 = []string{"IsDir__boo", "Data__bin", "SyncedData__bin", "ModTime__tim", "Children__map", "SyncedChildren__map"}

var decodeMsgFieldSkip26zgensym_965f3afadc761adf_27 = []bool{false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *SerzMemNode) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 6
	}
	var fieldsInUse uint32 = 6
	isempty[0] = (!z.IsDir) // bool, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Data) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.SyncedData) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (z.ModTime.IsZero()) // time.Time, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (len(z.Children) == 0) // string, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.SyncedChildren) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *SerzMemNode) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_965f3afadc761adf_30 [6]bool
	fieldsInUse_zgensym_965f3afadc761adf_31 := z.fieldsNotEmpty(empty_zgensym_965f3afadc761adf_30[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_965f3afadc761adf_31 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'SerzMemNode'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x53, 0x65, 0x72, 0x7a, 0x4d, 0x65, 0x6d, 0x4e, 0x6f, 0x64, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_965f3afadc761adf_30[0] {
		// write "IsDir__boo"
		err = en.Append(0xaa, 0x49, 0x73, 0x44, 0x69, 0x72, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		if err != nil {
			return err
		}
		err = en.WriteBool(z.IsDir)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_30[1] {
		// write "Data__bin"
		err = en.Append(0xa9, 0x44, 0x61, 0x74, 0x61, 0x5f, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Data)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_30[2] {
		// write "SyncedData__bin"
		err = en.Append(0xaf, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x5f, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.SyncedData)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_30[3] {
		// write "ModTime__tim"
		err = en.Append(0xac, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x5f, 0x74, 0x69, 0x6d)
		if err != nil {
			return err
		}
		err = en.WriteTime(z.ModTime)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_965f3afadc761adf_30[4] {
		// write "Children__map"
		err = en.Append(0xad, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		if err != nil {
			return err
		}
		err = en.WriteMapHeader(uint32(len(z.Children)))
		if err != nil {
			return
		}
		for zgensym_965f3afadc761adf_22, zgensym_965f3afadc761adf_23 := range z.Children {
			err = en.WriteString(zgensym_965f3afadc761adf_22)
			if err != nil {
				return
			}
			// gPtr.encodeGen():

			if zgensym_965f3afadc761adf_23 == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = zgensym_965f3afadc761adf_23.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	if !empty_zgensym_965f3afadc761adf_30[5] {
		// write "SyncedChildren__map"
		err = en.Append(0xb3, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		if err != nil {
			return err
		}
		err = en.WriteMapHeader(uint32(len(z.SyncedChildren)))
		if err != nil {
			return
		}
		for zgensym_965f3afadc761adf_24, zgensym_965f3afadc761adf_25 := range z.SyncedChildren {
			err = en.WriteString(zgensym_965f3afadc761adf_24)
			if err != nil {
				return
			}
			// gPtr.encodeGen():

			if zgensym_965f3afadc761adf_25 == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = zgensym_965f3afadc761adf_25.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SerzMemNode) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [6]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "IsDir__boo"
		o = append(o, 0xaa, 0x49, 0x73, 0x44, 0x69, 0x72, 0x5f, 0x5f, 0x62, 0x6f, 0x6f)
		o = msgp.AppendBool(o, z.IsDir)
	}

	if !empty[1] {
		// string "Data__bin"
		o = append(o, 0xa9, 0x44, 0x61, 0x74, 0x61, 0x5f, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Data)
	}

	if !empty[2] {
		// string "SyncedData__bin"
		o = append(o, 0xaf, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x5f, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.SyncedData)
	}

	if !empty[3] {
		// string "ModTime__tim"
		o = append(o, 0xac, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x5f, 0x74, 0x69, 0x6d)
		o = msgp.AppendTime(o, z.ModTime)
	}

	if !empty[4] {
		// string "Children__map"
		o = append(o, 0xad, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		o = msgp.AppendMapHeader(o, uint32(len(z.Children)))
		for zgensym_965f3afadc761adf_22, zgensym_965f3afadc761adf_23 := range z.Children {
			o = msgp.AppendString(o, zgensym_965f3afadc761adf_22)
			// marshalGen.gPtr()

			if zgensym_965f3afadc761adf_23 == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				o, err = zgensym_965f3afadc761adf_23.MarshalMsg(o) // not is.iface
				if err != nil {
					return
				}
			}
		}
	}

	if !empty[5] {
		// string "SyncedChildren__map"
		o = append(o, 0xb3, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x5f, 0x6d, 0x61, 0x70)
		o = msgp.AppendMapHeader(o, uint32(len(z.SyncedChildren)))
		for zgensym_965f3afadc761adf_24, zgensym_965f3afadc761adf_25 := range z.SyncedChildren {
			o = msgp.AppendString(o, zgensym_965f3afadc761adf_24)
			// marshalGen.gPtr()

			if zgensym_965f3afadc761adf_25 == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				o, err = zgensym_965f3afadc761adf_25.MarshalMsg(o) // not is.iface
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SerzMemNode) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *SerzMemNode) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields32zgensym_965f3afadc761adf_33 = 6

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields32zgensym_965f3afadc761adf_33 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields32zgensym_965f3afadc761adf_33, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft32zgensym_965f3afadc761adf_33 := totalEncodedFields32zgensym_965f3afadc761adf_33
	missingFieldsLeft32zgensym_965f3afadc761adf_33 := maxFields32zgensym_965f3afadc761adf_33 - totalEncodedFields32zgensym_965f3afadc761adf_33

	var nextMiss32zgensym_965f3afadc761adf_33 int32 = -1
	var found32zgensym_965f3afadc761adf_33 [maxFields32zgensym_965f3afadc761adf_33]bool
	var curField32zgensym_965f3afadc761adf_33 string

doneWithStruct32zgensym_965f3afadc761adf_33:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft32zgensym_965f3afadc761adf_33 > 0 || missingFieldsLeft32zgensym_965f3afadc761adf_33 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft32zgensym_965f3afadc761adf_33, missingFieldsLeft32zgensym_965f3afadc761adf_33, msgp.ShowFound(found32zgensym_965f3afadc761adf_33[:]), unmarshalMsgFieldOrder32zgensym_965f3afadc761adf_33)
		if encodedFieldsLeft32zgensym_965f3afadc761adf_33 > 0 {
			encodedFieldsLeft32zgensym_965f3afadc761adf_33--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField32zgensym_965f3afadc761adf_33 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss32zgensym_965f3afadc761adf_33 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss32zgensym_965f3afadc761adf_33 = 0
			}
			for nextMiss32zgensym_965f3afadc761adf_33 < maxFields32zgensym_965f3afadc761adf_33 && (found32zgensym_965f3afadc761adf_33[nextMiss32zgensym_965f3afadc761adf_33] || unmarshalMsgFieldSkip32zgensym_965f3afadc761adf_33[nextMiss32zgensym_965f3afadc761adf_33]) {
				nextMiss32zgensym_965f3afadc761adf_33++
			}
			if nextMiss32zgensym_965f3afadc761adf_33 == maxFields32zgensym_965f3afadc761adf_33 {
				// filled all the empty fields!
				break doneWithStruct32zgensym_965f3afadc761adf_33
			}
			missingFieldsLeft32zgensym_965f3afadc761adf_33--
			curField32zgensym_965f3afadc761adf_33 = unmarshalMsgFieldOrder32zgensym_965f3afadc761adf_33[nextMiss32zgensym_965f3afadc761adf_33]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField32zgensym_965f3afadc761adf_33)
		switch curField32zgensym_965f3afadc761adf_33 {
		// -- templateUnmarshalMsg ends here --

		case "IsDir__boo":
			found32zgensym_965f3afadc761adf_33[0] = true
			z.IsDir, bts, err = nbs.ReadBoolBytes(bts)

			if err != nil {
				return
			}
		case "Data__bin":
			found32zgensym_965f3afadc761adf_33[1] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Data = z.Data[:0]
			} else {
				z.Data, bts, err = nbs.ReadBytesBytes(bts, z.Data)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		case "SyncedData__bin":
			found32zgensym_965f3afadc761adf_33[2] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.SyncedData = z.SyncedData[:0]
			} else {
				z.SyncedData, bts, err = nbs.ReadBytesBytes(bts, z.SyncedData)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		case "ModTime__tim":
			found32zgensym_965f3afadc761adf_33[3] = true
			z.ModTime, bts, err = nbs.ReadTimeBytes(bts)

			if err != nil {
				return
			}
		case "Children__map":
			found32zgensym_965f3afadc761adf_33[4] = true
			if nbs.AlwaysNil {
				if len(z.Children) > 0 {
					for key, _ := range z.Children {
						delete(z.Children, key)
					}
				}

			} else {

				var zgensym_965f3afadc761adf_34 uint32
				zgensym_965f3afadc761adf_34, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
				if z.Children == nil && zgensym_965f3afadc761adf_34 > 0 {
					z.Children = make(map[string]*SerzMemNode, zgensym_965f3afadc761adf_34)
				} else if len(z.Children) > 0 {
					for key, _ := range z.Children {
						delete(z.Children, key)
					}
				}
				for zgensym_965f3afadc761adf_34 > 0 {
					var zgensym_965f3afadc761adf_22 string
					var zgensym_965f3afadc761adf_23 *SerzMemNode
					zgensym_965f3afadc761adf_34--
					zgensym_965f3afadc761adf_22, bts, err = nbs.ReadStringBytes(bts)
					if err != nil {
						return
					}
					// unmarshalGen.gPtr(): we have a BaseElem.

					// unmarshalGen.gPtr(): we have an IDENT:

					if nbs.AlwaysNil {
						if zgensym_965f3afadc761adf_23 != nil {
							zgensym_965f3afadc761adf_23.UnmarshalMsg(msgp.OnlyNilSlice)
						}
					} else {
						// not nbs.AlwaysNil
						if msgp.IsNil(bts) {
							bts = bts[1:]
							if nil != zgensym_965f3afadc761adf_23 {
								zgensym_965f3afadc761adf_23.UnmarshalMsg(msgp.OnlyNilSlice)
							}
						} else {
							// not nbs.AlwaysNil and not IsNil(bts): have something to read

							if zgensym_965f3afadc761adf_23 == nil {
								zgensym_965f3afadc761adf_23 = new(SerzMemNode)
							}

							bts, err = zgensym_965f3afadc761adf_23.UnmarshalMsg(bts)
							if err != nil {
								return
							}
						}
					}
					z.Children[zgensym_965f3afadc761adf_22] = zgensym_965f3afadc761adf_23
				}
			}
		case "SyncedChildren__map":
			found32zgensym_965f3afadc761adf_33[5] = true
			if nbs.AlwaysNil {
				if len(z.SyncedChildren) > 0 {
					for key, _ := range z.SyncedChildren {
						delete(z.SyncedChildren, key)
					}
				}

			} else {

				var zgensym_965f3afadc761adf_35 uint32
				zgensym_965f3afadc761adf_35, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
				if z.SyncedChildren == nil && zgensym_965f3afadc761adf_35 > 0 {
					z.SyncedChildren = make(map[string]*SerzMemNode, zgensym_965f3afadc761adf_35)
				} else if len(z.SyncedChildren) > 0 {
					for key, _ := range z.SyncedChildren {
						delete(z.SyncedChildren, key)
					}
				}
				for zgensym_965f3afadc761adf_35 > 0 {
					var zgensym_965f3afadc761adf_24 string
					var zgensym_965f3afadc761adf_25 *SerzMemNode
					zgensym_965f3afadc761adf_35--
					zgensym_965f3afadc761adf_24, bts, err = nbs.ReadStringBytes(bts)
					if err != nil {
						return
					}
					// unmarshalGen.gPtr(): we have a BaseElem.

					// unmarshalGen.gPtr(): we have an IDENT:

					if nbs.AlwaysNil {
						if zgensym_965f3afadc761adf_25 != nil {
							zgensym_965f3afadc761adf_25.UnmarshalMsg(msgp.OnlyNilSlice)
						}
					} else {
						// not nbs.AlwaysNil
						if msgp.IsNil(bts) {
							bts = bts[1:]
							if nil != zgensym_965f3afadc761adf_25 {
								zgensym_965f3afadc761adf_25.UnmarshalMsg(msgp.OnlyNilSlice)
							}
						} else {
							// not nbs.AlwaysNil and not IsNil(bts): have something to read

							if zgensym_965f3afadc761adf_25 == nil {
								zgensym_965f3afadc761adf_25 = new(SerzMemNode)
							}

							bts, err = zgensym_965f3afadc761adf_25.UnmarshalMsg(bts)
							if err != nil {
								return
							}
						}
					}
					z.SyncedChildren[zgensym_965f3afadc761adf_24] = zgensym_965f3afadc761adf_25
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss32zgensym_965f3afadc761adf_33 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of SerzMemNode
var unmarshalMsgFieldOrder32zgensym_965f3afadc761adf_33 = []string{"IsDir__boo", "Data__bin", "SyncedData__bin", "ModTime__tim", "Children__map", "SyncedChildren__map"}

var unmarshalMsgFieldSkip32zgensym_965f3afadc761adf_33 = []bool{false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SerzMemNode) Msgsize() (s int) {
	s = 1 + 11 + msgp.BoolSize + 10 + msgp.BytesPrefixSize + len(z.Data) + 16 + msgp.BytesPrefixSize + len(z.SyncedData) + 13 + msgp.TimeSize + 14 + msgp.MapHeaderSize
	if z.Children != nil {
		for zgensym_965f3afadc761adf_22, zgensym_965f3afadc761adf_23 := range z.Children {
			_ = zgensym_965f3afadc761adf_23
			_ = zgensym_965f3afadc761adf_22
			s += msgp.StringPrefixSize + len(zgensym_965f3afadc761adf_22)
			if zgensym_965f3afadc761adf_23 == nil {
				s += msgp.NilSize
			} else {
				s += zgensym_965f3afadc761adf_23.Msgsize()
			}
		}
	}
	s += 20 + msgp.MapHeaderSize
	if z.SyncedChildren != nil {
		for zgensym_965f3afadc761adf_24, zgensym_965f3afadc761adf_25 := range z.SyncedChildren {
			_ = zgensym_965f3afadc761adf_25
			_ = zgensym_965f3afadc761adf_24
			s += msgp.StringPrefixSize + len(zgensym_965f3afadc761adf_24)
			if zgensym_965f3afadc761adf_25 == nil {
				s += msgp.NilSize
			} else {
				s += zgensym_965f3afadc761adf_25.Msgsize()
			}
		}
	}
	return
}
func (z *SerzMemNode) Gstring() (r string) {
	r = "&SerzMemNode{\n"
	r += fmt.Sprintf("         IsDir: %v,\n", z.IsDir)
	r += fmt.Sprintf("          Data: %v,\n", z.Data)
	r += fmt.Sprintf("    SyncedData: %v,\n", z.SyncedData)
	r += fmt.Sprintf("       ModTime: %v,\n", z.ModTime)
	r += fmt.Sprintf("      Children: %v,\n", z.Children)
	r += fmt.Sprintf("SyncedChildren: %v,\n", z.SyncedChildren)
	r += "}\n"
	return
}
